#!/usr/bin/env python3
"""Generate a slide index for every SPOKES lesson deck.

Maps the on-screen slide number (the "Slide N of M" counter) to the source
line number and a human-readable title, so a reviewer can say "slide 14" and
the exact markup can be located without counting sections by hand.

The index is regenerated rather than hand-maintained because line numbers
drift every time a deck is edited.

Usage:
    python3 scripts/slide-index.py            # write docs/slide-index.md
    python3 scripts/slide-index.py --stdout   # print instead of writing
    python3 scripts/slide-index.py --lesson lesson-time-management
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "slide-index.md"
LESSON_GLOB = "lesson-*/index.html"

SLIDE_OPEN_RE = re.compile(r'<section\s+class="(slide[^"]*)"([^>]*)>')
CHAPTER_RE = re.compile(r'data-chapter="([^"]*)"')
SIDEBAR_TITLE_RE = re.compile(r'data-sidebar-title="([^"]*)"')
HEADING_RE = re.compile(r"<h[1-4][^>]*>(.*?)</h[1-4]>", re.DOTALL)
COMMENT_RE = re.compile(r"<!--\s*Slide\s*\d*\s*:?\s*(.*?)\s*-->")
TAG_RE = re.compile(r"<[^>]+>")

# Classes that describe a slide's role, minus the generic "slide" marker.
TYPE_PREFIX = "slide-"
NOTABLE_CLASSES = ("big-statement", "active")

MAX_TITLE_LEN = 70
TITLE_LOOKAHEAD_LINES = 40


def strip_markup(fragment):
    """Reduce an HTML fragment to a single line of readable text."""
    text = TAG_RE.sub(" ", fragment)
    text = re.sub(r"&[a-zA-Z]+;|&#\d+;", " ", text)
    return " ".join(text.split())


def truncate(text, limit=MAX_TITLE_LEN):
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def slide_type(class_attr):
    """Human label for a slide's role, derived from its classes."""
    parts = [
        cls[len(TYPE_PREFIX):] if cls.startswith(TYPE_PREFIX) else cls
        for cls in class_attr.split()
        if cls != "slide" and (cls.startswith(TYPE_PREFIX) or cls in NOTABLE_CLASSES)
    ]
    labels = [part for part in parts if part != "active"]
    return ", ".join(labels) if labels else "content"


def find_title(lines, start_index, end_index):
    """Best-effort slide title: first heading, else sidebar title, else comment."""
    window = "\n".join(lines[start_index:min(end_index, start_index + TITLE_LOOKAHEAD_LINES)])

    heading = HEADING_RE.search(window)
    if heading:
        text = strip_markup(heading.group(1))
        if text:
            return text

    sidebar = SIDEBAR_TITLE_RE.search(lines[start_index])
    if sidebar:
        return sidebar.group(1)

    # Fall back to the authoring comment that precedes the section, if any.
    for offset in range(1, 4):
        probe = start_index - offset
        if probe < 0:
            break
        comment = COMMENT_RE.search(lines[probe])
        if comment and comment.group(1):
            return strip_markup(comment.group(1))

    return "(no heading)"


def index_lesson(html_path):
    """Return a list of slide records for one lesson deck."""
    try:
        lines = html_path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise SystemExit(f"error: cannot read {html_path}: {exc}")

    openings = [
        (line_index, match)
        for line_index, line in enumerate(lines)
        if (match := SLIDE_OPEN_RE.search(line))
    ]

    records = []
    for position, (line_index, match) in enumerate(openings):
        next_index = openings[position + 1][0] if position + 1 < len(openings) else len(lines)
        chapter = CHAPTER_RE.search(match.group(2))
        records.append({
            "number": position + 1,
            "line": line_index + 1,
            "type": slide_type(match.group(1)),
            "chapter": chapter.group(1) if chapter else "-",
            "title": truncate(find_title(lines, line_index, next_index)),
        })
    return records


def render_lesson(lesson_name, records):
    lines = [
        f"## {lesson_name}",
        "",
        f"{len(records)} slides &middot; `{lesson_name}/index.html`",
        "",
        "| Slide | Line | Ch | Type | Title |",
        "|------:|-----:|:--:|------|-------|",
    ]
    lines += [
        "| {number} | {line} | {chapter} | {type} | {title} |".format(**record)
        for record in records
    ]
    lines.append("")
    return lines


def render_document(lessons):
    total = sum(len(records) for _, records in lessons)
    header = [
        "# Slide Index",
        "",
        "Generated by `scripts/slide-index.py` — do not edit by hand.",
        "Regenerate after editing any deck: `python3 scripts/slide-index.py`",
        "",
        f"**{total} slides across {len(lessons)} lessons.** "
        "Slide numbers match the on-screen `Slide N of M` counter.",
        "",
    ]
    body = []
    for lesson_name, records in lessons:
        body += render_lesson(lesson_name, records)
    return "\n".join(header + body)


def main():
    parser = argparse.ArgumentParser(description="Generate the SPOKES slide index.")
    parser.add_argument("--lesson", help="Index only this lesson directory.")
    parser.add_argument("--stdout", action="store_true", help="Print instead of writing.")
    args = parser.parse_args()

    paths = sorted(REPO_ROOT.glob(LESSON_GLOB))
    if args.lesson:
        wanted = args.lesson.rstrip("/")
        paths = [path for path in paths if path.parent.name == wanted]
        if not paths:
            raise SystemExit(f"error: no lesson directory named {wanted!r}")

    if not paths:
        raise SystemExit("error: no lesson decks found")

    lessons = [(path.parent.name, index_lesson(path)) for path in paths]
    document = render_document(lessons)

    if args.stdout:
        print(document)
        return

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(document + "\n", encoding="utf-8")
    total = sum(len(records) for _, records in lessons)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} — {total} slides, {len(lessons)} lessons.")


if __name__ == "__main__":
    sys.exit(main())
